[package]
name = "rhino2d-wgpu"
description = "wgpu renderer for Inochi2D models"
version = "0.1.0"
edition = "2021"

[dependencies]
rhino2d-engine = { path = "../rhino2d-engine", version = "0.1.0" }
rhino2d-io = { path = "../rhino2d-io", version = "0.1.0" }
wgpu = "0.12.0"
image = "0.24.2"
